# Generated by Django 4.0.6 on 2022-08-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
