# Generated by Django 4.0.6 on 2022-08-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_product_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
