# Generated by Django 4.0.6 on 2022-08-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_featureproduct_fproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('bimage', models.ImageField(upload_to='uploads/brands/')),
            ],
        ),
        migrations.DeleteModel(
            name='FeatureProduct',
        ),
    ]
