# Generated by Django 4.0.6 on 2022-08-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cus_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
