# Generated by Django 4.0.6 on 2022-08-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_cus_name_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.category'),
        ),
    ]
