# Generated by Django 4.0.6 on 2022-08-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_category_description_category_image_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=1, help_text='0-show,1-Hidden'),
        ),
    ]
