# Generated by Django 4.0.6 on 2022-08-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cname',
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
