# Generated by Django 4.0.6 on 2022-08-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_rename_name_category_cname_alter_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cname',
            new_name='name',
        ),
    ]
