# Generated by Django 4.0.6 on 2022-08-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_category_slug_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
