# Generated by Django 4.0.6 on 2022-08-15 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_remove_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app1.product')),
            ],
        ),
    ]
