# Generated by Django 4.0.6 on 2022-08-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.product', to_field='pname'),
        ),
    ]
