# Generated by Django 4.0.6 on 2022-08-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_product_pname_alter_productdetails_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productdetails',
        ),
    ]
