# Generated by Django 4.0.6 on 2022-08-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_delete_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
